using System.Linq.Expressions; using BuildingBlocks.Grids; using BuildingBlocks.Messaging; using Expenses.Contracts; using Expenses.Domain; using Expenses.Persistence; using FluentValidation; using MapsterMapper; using Microsoft.EntityFrameworkCore; using SharedKernel;
namespace Expenses.Features;
/** <summary>Create command.</summary> */ public sealed record CreateExpenseCommand(string Category,decimal Amount,DateOnly Date,string Payee,string? Notes):ICommand<ExpenseResponse>;
/** <summary>Update command.</summary> */ public sealed record UpdateExpenseCommand(Guid Id,string Category,decimal Amount,DateOnly Date,string Payee,string? Notes):ICommand<ExpenseResponse>;
/** <summary>Delete command.</summary> */ public sealed record DeleteExpenseCommand(Guid Id):ICommand<bool>;
/** <summary>Get query.</summary> */ public sealed record GetExpenseByIdQuery(Guid Id):IQuery<ExpenseResponse>;
/** <summary>Grid query.</summary> */ public sealed record GetExpensesGridQuery(GridQuery Grid):IQuery<PagedResult<ExpenseResponse>>;
/** <summary>Create validator.</summary> */ public sealed class CreateExpenseValidator:AbstractValidator<CreateExpenseCommand>{/** <summary>Rules.</summary> */ public CreateExpenseValidator(){RuleFor(x=>x.Category).NotEmpty();RuleFor(x=>x.Amount).GreaterThan(0);RuleFor(x=>x.Payee).NotEmpty();}}
/** <summary>Expense grid.</summary> */ public static class ExpenseGrid
{
    /** <summary>Fields.</summary> */ public static readonly GridFieldMap<Expense> Fields=new(new[]{(new GridField("category","الفئة",GridFieldType.Text,true,Chartable:true),(Expression<Func<Expense,object?>>)(x=>x.Category)),(new GridField("amount","المبلغ",GridFieldType.Number,false,Chartable:true),x=>x.Amount),(new GridField("date","التاريخ",GridFieldType.Date,false,Chartable:true),x=>x.Date),(new GridField("payee","المستفيد",GridFieldType.Text,true),x=>x.Payee),(new GridField("createdAt","تاريخ الإنشاء",GridFieldType.Date,false),x=>x.CreatedAtUtc)});
    /** <summary>Projection.</summary> */ public static readonly Expression<Func<Expense,ExpenseResponse>> Projection=x=>new(x.Id,x.Category,x.Amount,x.Date,x.Payee,x.Notes,x.CreatedAtUtc,x.UpdatedAtUtc);
}
/** <summary>Create handler.</summary> */ public sealed class CreateExpenseHandler(IExpenseRepository repo,IMapper mapper):ICommandHandler<CreateExpenseCommand,ExpenseResponse>{/** <inheritdoc/> */ public async Task<Result<ExpenseResponse>> Handle(CreateExpenseCommand c,CancellationToken ct){var e=Expense.Create(c.Category,c.Amount,c.Date,c.Payee,c.Notes);if(e.IsFailure)return e.Error;repo.Add(e.Value);await repo.SaveChangesAsync(ct);return mapper.Map<ExpenseResponse>(e.Value);}}
/** <summary>Update handler.</summary> */ public sealed class UpdateExpenseHandler(IExpenseRepository repo,IMapper mapper):ICommandHandler<UpdateExpenseCommand,ExpenseResponse>{/** <inheritdoc/> */ public async Task<Result<ExpenseResponse>> Handle(UpdateExpenseCommand c,CancellationToken ct){var e=await repo.GetByIdAsync(c.Id,ct);if(e is null)return ExpenseErrors.NotFound(c.Id);var r=e.Update(c.Category,c.Amount,c.Date,c.Payee,c.Notes);if(r.IsFailure)return r.Error;await repo.SaveChangesAsync(ct);return mapper.Map<ExpenseResponse>(e);}}
/** <summary>Delete handler.</summary> */ public sealed class DeleteExpenseHandler(IExpenseRepository repo):ICommandHandler<DeleteExpenseCommand,bool>{/** <inheritdoc/> */ public async Task<Result<bool>> Handle(DeleteExpenseCommand c,CancellationToken ct){var e=await repo.GetByIdAsync(c.Id,ct);if(e is null)return ExpenseErrors.NotFound(c.Id);repo.Remove(e);await repo.SaveChangesAsync(ct);return true;}}
/** <summary>Get handler.</summary> */ public sealed class GetExpenseByIdHandler(IExpenseRepository repo,IMapper mapper):IQueryHandler<GetExpenseByIdQuery,ExpenseResponse>{/** <inheritdoc/> */ public async Task<Result<ExpenseResponse>> Handle(GetExpenseByIdQuery q,CancellationToken ct){var e=await repo.GetByIdAsync(q.Id,ct);return e is null?ExpenseErrors.NotFound(q.Id):mapper.Map<ExpenseResponse>(e);}}
/** <summary>Grid handler.</summary> */ public sealed class GetExpensesGridHandler(ExpensesDbContext db):IQueryHandler<GetExpensesGridQuery,PagedResult<ExpenseResponse>>{/** <inheritdoc/> */ public async Task<Result<PagedResult<ExpenseResponse>>> Handle(GetExpensesGridQuery q,CancellationToken ct){var r=db.Expenses.AsNoTracking().ApplyGridQuery(q.Grid,ExpenseGrid.Fields);if(r.IsFailure)return r.Error;return await r.Value.ToPagedResultAsync(q.Grid,ExpenseGrid.Projection,ct);}}
