
using BuildingBlocks.Ledger;using Expenses.Domain;using Expenses.Persistence;using Microsoft.EntityFrameworkCore;
namespace Expenses.Ledger;
/// <summary>Expense ledger source.</summary>
public sealed class ExpensesLedgerSource(IMainDbContext db):ILedgerSource{public LedgerKind Kind=>LedgerKind.Expense;public async Task<IReadOnlyList<LedgerEntry>> GetEntriesAsync(OwnerType ownerType,Guid ownerId,DateOnly? from,DateOnly? to,CancellationToken ct){var q=from e in db.Set<Expense>().AsNoTracking() join t in db.Set<ExpenseType>() on e.ExpenseTypeId equals t.Id where e.OwnerType==ownerType&&e.OwnerId==ownerId select new{e,t};if(from.HasValue)q=q.Where(x=>x.e.Date>=from.Value);if(to.HasValue)q=q.Where(x=>x.e.Date<=to.Value);return await q.Select(x=>new LedgerEntry(x.e.Id,Kind,x.e.OwnerType,x.e.OwnerId,x.t.Name,x.e.Amount,x.e.Date)).ToListAsync(ct);}public async Task<IReadOnlyDictionary<Guid,decimal>> GetTotalsAsync(OwnerType ownerType,IReadOnlyCollection<Guid> ids,DateOnly? from,DateOnly? to,CancellationToken ct){var q=db.Set<Expense>().AsNoTracking().Where(x=>x.OwnerType==ownerType&&x.OwnerId.HasValue&&ids.Contains(x.OwnerId.Value));if(from.HasValue)q=q.Where(x=>x.Date>=from.Value);if(to.HasValue)q=q.Where(x=>x.Date<=to.Value);return await q.GroupBy(x=>x.OwnerId!.Value).ToDictionaryAsync(x=>x.Key,x=>x.Sum(v=>v.Amount),ct);}}
/// <summary>Expense ledger writer.</summary>
public sealed class ExpensesLedgerWriter(IMainDbContext db):ILedgerWriter{public async Task<Guid> CreateExpenseAsync(OwnerType ownerType,Guid ownerId,Guid typeId,decimal amount,DateOnly date,string payee,string? notes,CancellationToken ct){if(!await db.Set<ExpenseType>().AnyAsync(x=>x.Id==typeId,ct))throw new ArgumentException("Unknown expense type.",nameof(typeId));var result=Expense.Create(typeId,amount,date,payee,notes,ownerType,ownerId);if(result.IsFailure)throw new ArgumentException(result.Error.Description);db.Set<Expense>().Add(result.Value);await db.SaveChangesAsync(ct);return result.Value.Id;}}


