using System.Linq.Expressions;using BuildingBlocks.Grids;using BuildingBlocks.Messaging;using FluentValidation;using MapsterMapper;using Microsoft.EntityFrameworkCore;using SharedKernel;using Todos.Contracts;using Todos.Domain;using Todos.Persistence;
namespace Todos.Features;
/** <summary>Create command.</summary> */ public sealed record CreateTodoCommand(string Title,DateOnly DueDate,TodoPriority Priority,string? Notes):ICommand<TodoResponse>;/** <summary>Update.</summary> */ public sealed record UpdateTodoCommand(Guid Id,string Title,DateOnly DueDate,TodoPriority Priority,string? Notes):ICommand<TodoResponse>;/** <summary>Status.</summary> */ public sealed record ChangeTodoStatusCommand(Guid Id,TodoStatus Status):ICommand<TodoResponse>;/** <summary>Delete.</summary> */ public sealed record DeleteTodoCommand(Guid Id):ICommand<bool>;/** <summary>Get.</summary> */ public sealed record GetTodoByIdQuery(Guid Id):IQuery<TodoResponse>;/** <summary>Grid.</summary> */ public sealed record GetTodosGridQuery(GridQuery Grid):IQuery<PagedResult<TodoResponse>>;
/** <summary>Validator.</summary> */ public sealed class CreateTodoValidator:AbstractValidator<CreateTodoCommand>{/** <summary>Rules.</summary> */ public CreateTodoValidator(){RuleFor(x=>x.Title).NotEmpty();}}
/** <summary>Grid metadata.</summary> */ public static class TodoGrid{/** <summary>Fields.</summary> */ public static readonly GridFieldMap<TodoItem> Fields=new(new[]{(new GridField("title","المهمة",GridFieldType.Text,true),(Expression<Func<TodoItem,object?>>)(x=>x.Title)),(new GridField("dueDate","تاريخ الاستحقاق",GridFieldType.Date,false,Chartable:true),x=>x.DueDate),(new GridField("status","الحالة",GridFieldType.Enum,false,Chartable:true),x=>x.Status),(new GridField("priority","الأولوية",GridFieldType.Enum,false,Chartable:true),x=>x.Priority),(new GridField("createdAt","تاريخ الإنشاء",GridFieldType.Date,false),x=>x.CreatedAtUtc)});/** <summary>Projection.</summary> */ public static readonly Expression<Func<TodoItem,TodoResponse>> Projection=x=>new(x.Id,x.Title,x.DueDate,x.Status,x.Priority,x.Notes,x.CreatedAtUtc,x.UpdatedAtUtc);}
/** <summary>Create handler.</summary> */ public sealed class CreateTodoHandler(ITodoRepository r,IMapper m):ICommandHandler<CreateTodoCommand,TodoResponse>{/** <inheritdoc/> */ public async Task<Result<TodoResponse>> Handle(CreateTodoCommand c,CancellationToken ct){var x=TodoItem.Create(c.Title,c.DueDate,c.Priority,c.Notes);if(x.IsFailure)return x.Error;r.Add(x.Value);await r.SaveChangesAsync(ct);return m.Map<TodoResponse>(x.Value);}}
/** <summary>Update handler.</summary> */ public sealed class UpdateTodoHandler(ITodoRepository r,IMapper m):ICommandHandler<UpdateTodoCommand,TodoResponse>{/** <inheritdoc/> */ public async Task<Result<TodoResponse>> Handle(UpdateTodoCommand c,CancellationToken ct){var x=await r.GetByIdAsync(c.Id,ct);if(x is null)return TodoErrors.NotFound(c.Id);var z=x.Update(c.Title,c.DueDate,c.Priority,c.Notes,DateOnly.FromDateTime(DateTime.UtcNow));if(z.IsFailure)return z.Error;await r.SaveChangesAsync(ct);return m.Map<TodoResponse>(x);}}
/** <summary>Status handler.</summary> */ public sealed class ChangeTodoStatusHandler(ITodoRepository r,IMapper m):ICommandHandler<ChangeTodoStatusCommand,TodoResponse>{/** <inheritdoc/> */ public async Task<Result<TodoResponse>> Handle(ChangeTodoStatusCommand c,CancellationToken ct){var x=await r.GetByIdAsync(c.Id,ct);if(x is null)return TodoErrors.NotFound(c.Id);x.ChangeStatus(c.Status);await r.SaveChangesAsync(ct);return m.Map<TodoResponse>(x);}}
/** <summary>Delete handler.</summary> */ public sealed class DeleteTodoHandler(ITodoRepository r):ICommandHandler<DeleteTodoCommand,bool>{/** <inheritdoc/> */ public async Task<Result<bool>> Handle(DeleteTodoCommand c,CancellationToken ct){var x=await r.GetByIdAsync(c.Id,ct);if(x is null)return TodoErrors.NotFound(c.Id);r.Remove(x);await r.SaveChangesAsync(ct);return true;}}
/** <summary>Get handler.</summary> */ public sealed class GetTodoByIdHandler(ITodoRepository r,IMapper m):IQueryHandler<GetTodoByIdQuery,TodoResponse>{/** <inheritdoc/> */ public async Task<Result<TodoResponse>> Handle(GetTodoByIdQuery q,CancellationToken ct){var x=await r.GetByIdAsync(q.Id,ct);return x is null?TodoErrors.NotFound(q.Id):m.Map<TodoResponse>(x);}}
/** <summary>Grid handler.</summary> */ public sealed class GetTodosGridHandler(TodosDbContext db):IQueryHandler<GetTodosGridQuery,PagedResult<TodoResponse>>{/** <inheritdoc/> */ public async Task<Result<PagedResult<TodoResponse>>> Handle(GetTodosGridQuery q,CancellationToken ct){var x=db.Items.AsNoTracking().ApplyGridQuery(q.Grid,TodoGrid.Fields);if(x.IsFailure)return x.Error;return await x.Value.ToPagedResultAsync(q.Grid,TodoGrid.Projection,ct);}}
