using SharedKernel; namespace Todos.Domain;
/** <summary>Todo status.</summary> */ public enum TodoStatus{Open,InProgress,Done}
/** <summary>Todo priority.</summary> */ public enum TodoPriority{Low,Normal,High,Urgent}
/** <summary>Todo aggregate.</summary> */ public sealed class TodoItem:AggregateRoot
{/** <summary>Title.</summary> */ public string Title{get;private set;}=string.Empty;/** <summary>Due date.</summary> */ public DateOnly DueDate{get;private set;}/** <summary>Status.</summary> */ public TodoStatus Status{get;private set;}/** <summary>Priority.</summary> */ public TodoPriority Priority{get;private set;}/** <summary>Notes.</summary> */ public string? Notes{get;private set;}/** <summary>Created.</summary> */ public DateTime CreatedAtUtc{get;private set;}/** <summary>Updated.</summary> */ public DateTime UpdatedAtUtc{get;private set;}private TodoItem(){}private TodoItem(string title,DateOnly due,TodoPriority priority,string? notes):base(Guid.NewGuid()){Title=title;DueDate=due;Priority=priority;Notes=notes;Status=TodoStatus.Open;CreatedAtUtc=UpdatedAtUtc=DateTime.UtcNow;}
/** <summary>Creates todo.</summary> */ public static Result<TodoItem> Create(string? title,DateOnly due,TodoPriority priority,string? notes)=>Create(title,due,priority,notes,DateOnly.FromDateTime(DateTime.UtcNow));
/** <summary>Creates todo against supplied today.</summary> */ public static Result<TodoItem> Create(string? title,DateOnly due,TodoPriority priority,string? notes,DateOnly today){if(string.IsNullOrWhiteSpace(title))return TodoErrors.TitleRequired;if(due<today)return TodoErrors.DueDatePast;return new TodoItem(title.Trim(),due,priority,string.IsNullOrWhiteSpace(notes)?null:notes.Trim());}
/** <summary>Updates todo.</summary> */ public Result<TodoItem> Update(string? title,DateOnly due,TodoPriority priority,string? notes,DateOnly today){if(string.IsNullOrWhiteSpace(title))return TodoErrors.TitleRequired;if(due<today)return TodoErrors.DueDatePast;Title=title.Trim();DueDate=due;Priority=priority;Notes=string.IsNullOrWhiteSpace(notes)?null:notes.Trim();UpdatedAtUtc=DateTime.UtcNow;return this;}
/** <summary>Changes status.</summary> */ public Result<TodoItem> ChangeStatus(TodoStatus status){Status=status;UpdatedAtUtc=DateTime.UtcNow;return this;}}
